# The Knight's Tour
- The Knight moves around a standard 8x8 chessboard until it covers all squares.
- This generates a pattern of 64 numbers that can be used to develop a keyed stream transposition cipher.
- Cryptanalysis:
    * Brute force attack: 19,591,828,170,979,904 possible combinations for an 8x8 chess board (impractical

In [1]:
get_ascii_list = []
for i in range(126):
    get_ascii_list.append(chr(i))
get_ascii_list.append("₹")
get_ascii_list.append("$")

In [2]:
x = {0: 1, 1: 60, 2: 39, 3: 34, 4: 31, 5: 18, 6: 9, 7: 64, 8: 38, 9: 35, 10: 32, 11: 61, 12: 10, 13: 63, 14: 30, 15: 17, 
     16: 59, 17: 2, 18: 37, 19: 40, 20: 33, 21: 28, 22: 19, 23: 8, 24: 6, 25: 49, 26: 42, 27: 27, 28: 62, 29: 11, 30: 16, 
     31: 29, 32: 43, 33: 58, 34: 3, 35: 50, 36: 41, 37: 24, 38: 7, 39: 20, 40: 48, 41: 51, 42: 46, 43: 55, 44: 26, 45: 21, 
     46: 12, 47: 15, 48: 57, 49: 44, 50: 53, 51: 4, 52: 23, 53: 14, 54: 25, 55: 6, 56: 52, 57: 47, 58: 56, 59: 45, 60: 54, 
     61: 5, 62: 22, 63: 13}

In [3]:
y = []
for i in x.values():
    y.append(i)

In [4]:
for i in x.values():
    y.append(i+64)

In [5]:
z = {}
for i in range(len(y)):
    z[i] = y[i]
print(z)

{0: 1, 1: 60, 2: 39, 3: 34, 4: 31, 5: 18, 6: 9, 7: 64, 8: 38, 9: 35, 10: 32, 11: 61, 12: 10, 13: 63, 14: 30, 15: 17, 16: 59, 17: 2, 18: 37, 19: 40, 20: 33, 21: 28, 22: 19, 23: 8, 24: 6, 25: 49, 26: 42, 27: 27, 28: 62, 29: 11, 30: 16, 31: 29, 32: 43, 33: 58, 34: 3, 35: 50, 36: 41, 37: 24, 38: 7, 39: 20, 40: 48, 41: 51, 42: 46, 43: 55, 44: 26, 45: 21, 46: 12, 47: 15, 48: 57, 49: 44, 50: 53, 51: 4, 52: 23, 53: 14, 54: 25, 55: 6, 56: 52, 57: 47, 58: 56, 59: 45, 60: 54, 61: 5, 62: 22, 63: 13, 64: 65, 65: 124, 66: 103, 67: 98, 68: 95, 69: 82, 70: 73, 71: 128, 72: 102, 73: 99, 74: 96, 75: 125, 76: 74, 77: 127, 78: 94, 79: 81, 80: 123, 81: 66, 82: 101, 83: 104, 84: 97, 85: 92, 86: 83, 87: 72, 88: 70, 89: 113, 90: 106, 91: 91, 92: 126, 93: 75, 94: 80, 95: 93, 96: 107, 97: 122, 98: 67, 99: 114, 100: 105, 101: 88, 102: 71, 103: 84, 104: 112, 105: 115, 106: 110, 107: 119, 108: 90, 109: 85, 110: 76, 111: 79, 112: 121, 113: 108, 114: 117, 115: 68, 116: 87, 117: 78, 118: 89, 119: 70, 120: 116, 121: 1

In [6]:
get_knight_moves = []
for i in z.values():
    get_knight_moves.append(i)

In [7]:
print(len(get_knight_moves))
print(len(get_ascii_list))

128
128


In [8]:
knight_key = {}
for i in range(128):
    knight_key[get_ascii_list[i]] = get_knight_moves[i] 

In [9]:
print(knight_key)

{'\x00': 1, '\x01': 60, '\x02': 39, '\x03': 34, '\x04': 31, '\x05': 18, '\x06': 9, '\x07': 64, '\x08': 38, '\t': 35, '\n': 32, '\x0b': 61, '\x0c': 10, '\r': 63, '\x0e': 30, '\x0f': 17, '\x10': 59, '\x11': 2, '\x12': 37, '\x13': 40, '\x14': 33, '\x15': 28, '\x16': 19, '\x17': 8, '\x18': 6, '\x19': 49, '\x1a': 42, '\x1b': 27, '\x1c': 62, '\x1d': 11, '\x1e': 16, '\x1f': 29, ' ': 43, '!': 58, '"': 3, '#': 50, '$': 77, '%': 24, '&': 7, "'": 20, '(': 48, ')': 51, '*': 46, '+': 55, ',': 26, '-': 21, '.': 12, '/': 15, '0': 57, '1': 44, '2': 53, '3': 4, '4': 23, '5': 14, '6': 25, '7': 6, '8': 52, '9': 47, ':': 56, ';': 45, '<': 54, '=': 5, '>': 22, '?': 13, '@': 65, 'A': 124, 'B': 103, 'C': 98, 'D': 95, 'E': 82, 'F': 73, 'G': 128, 'H': 102, 'I': 99, 'J': 96, 'K': 125, 'L': 74, 'M': 127, 'N': 94, 'O': 81, 'P': 123, 'Q': 66, 'R': 101, 'S': 104, 'T': 97, 'U': 92, 'V': 83, 'W': 72, 'X': 70, 'Y': 113, 'Z': 106, '[': 91, '\\': 126, ']': 75, '^': 80, '_': 93, '`': 107, 'a': 122, 'b': 67, 'c': 114, 'd'

In [10]:
plainText = "Kanaad is a magi!"

In [11]:
cipherText = ""
for i in plainText:
    if ord(i) in z.keys():
        cipherText += f"{str(z[ord(i)])} "

In [12]:
print(cipherText)

125 122 76 122 122 105 43 115 68 43 122 43 85 122 84 115 58 


In [13]:
a = {}
for i in range(len(y)):
    a[y[i]] = i
print(a)

{1: 0, 60: 1, 39: 2, 34: 3, 31: 4, 18: 5, 9: 6, 64: 7, 38: 8, 35: 9, 32: 10, 61: 11, 10: 12, 63: 13, 30: 14, 17: 15, 59: 16, 2: 17, 37: 18, 40: 19, 33: 20, 28: 21, 19: 22, 8: 23, 6: 55, 49: 25, 42: 26, 27: 27, 62: 28, 11: 29, 16: 30, 29: 31, 43: 32, 58: 33, 3: 34, 50: 35, 41: 36, 24: 37, 7: 38, 20: 39, 48: 40, 51: 41, 46: 42, 55: 43, 26: 44, 21: 45, 12: 46, 15: 47, 57: 48, 44: 49, 53: 50, 4: 51, 23: 52, 14: 53, 25: 54, 52: 56, 47: 57, 56: 58, 45: 59, 54: 60, 5: 61, 22: 62, 13: 63, 65: 64, 124: 65, 103: 66, 98: 67, 95: 68, 82: 69, 73: 70, 128: 71, 102: 72, 99: 73, 96: 74, 125: 75, 74: 76, 127: 77, 94: 78, 81: 79, 123: 80, 66: 81, 101: 82, 104: 83, 97: 84, 92: 85, 83: 86, 72: 87, 70: 119, 113: 89, 106: 90, 91: 91, 126: 92, 75: 93, 80: 94, 93: 95, 107: 96, 122: 97, 67: 98, 114: 99, 105: 100, 88: 101, 71: 102, 84: 103, 112: 104, 115: 105, 110: 106, 119: 107, 90: 108, 85: 109, 76: 110, 79: 111, 121: 112, 108: 113, 117: 114, 68: 115, 87: 116, 78: 117, 89: 118, 116: 120, 111: 121, 120: 122, 1

In [14]:
def encryption(plainText):
    encryptionKey = {0: 1, 1: 60, 2: 39, 3: 34, 4: 31, 5: 18, 6: 9, 7: 64, 8: 38, 9: 35, 10: 32, 11: 61, 12: 10, 
                     13: 63, 14: 30, 15: 17, 16: 59, 17: 2, 18: 37, 19: 40, 20: 33, 21: 28, 22: 19, 23: 8, 24: 6, 
                     25: 49, 26: 42, 27: 27, 28: 62, 29: 11, 30: 16, 31: 29, 32: 43, 33: 58, 34: 3, 35: 50, 36: 41, 
                     37: 24, 38: 7, 39: 20, 40: 48, 41: 51, 42: 46, 43: 55, 44: 26, 45: 21, 46: 12, 47: 15, 48: 57, 
                     49: 44, 50: 53, 51: 4, 52: 23, 53: 14, 54: 25, 55: 6, 56: 52, 57: 47, 58: 56, 59: 45, 60: 54, 
                     61: 5, 62: 22, 63: 13, 64: 65, 65: 124, 66: 103, 67: 98, 68: 95, 69: 82, 70: 73, 71: 128, 72: 102, 
                     73: 99, 74: 96, 75: 125, 76: 74, 77: 127, 78: 94, 79: 81, 80: 123, 81: 66, 82: 101, 83: 104, 84: 97, 
                     85: 92, 86: 83, 87: 72, 88: 70, 89: 113, 90: 106, 91: 91, 92: 126, 93: 75, 94: 80, 95: 93, 96: 107, 
                     97: 122, 98: 67, 99: 114, 100: 105, 101: 88, 102: 71, 103: 84, 104: 112, 105: 115, 106: 110, 107: 119, 
                     108: 90, 109: 85, 110: 76, 111: 79, 112: 121, 113: 108, 114: 117, 115: 68, 116: 87, 117: 78, 118: 89, 
                     119: 70, 120: 116, 121: 111, 122: 120, 123: 109, 124: 118, 125: 69, 126: 86, 127: 77}
    cipherText = ""
    for i in plainText:
        if ord(i) in encryptionKey.keys():
            cipherText += f"{str(chr(encryptionKey[ord(i)]))}"
    return cipherText

In [15]:
def decryption(cipherText):
    decryptionKey = {1: 0, 60: 1, 39: 2, 34: 3, 31: 4, 18: 5, 9: 6, 64: 7, 38: 8, 35: 9, 32: 10, 61: 11, 10: 12, 63: 13, 
                     30: 14, 17: 15, 59: 16, 2: 17, 37: 18, 40: 19, 33: 20, 28: 21, 19: 22, 8: 23, 6: 55, 49: 25, 42: 26, 
                     27: 27, 62: 28, 11: 29, 16: 30, 29: 31, 43: 32, 58: 33, 3: 34, 50: 35, 41: 36, 24: 37, 7: 38, 20: 39, 
                     48: 40, 51: 41, 46: 42, 55: 43, 26: 44, 21: 45, 12: 46, 15: 47, 57: 48, 44: 49, 53: 50, 4: 51, 23: 52, 
                     14: 53, 25: 54, 52: 56, 47: 57, 56: 58, 45: 59, 54: 60, 5: 61, 22: 62, 13: 63, 65: 64, 124: 65, 103: 66, 
                     98: 67, 95: 68, 82: 69, 73: 70, 128: 71, 102: 72, 99: 73, 96: 74, 125: 75, 74: 76, 127: 77, 94: 78, 
                     81: 79, 123: 80, 66: 81, 101: 82, 104: 83, 97: 84, 92: 85, 83: 86, 72: 87, 70: 119, 113: 89, 106: 90, 
                     91: 91, 126: 92, 75: 93, 80: 94, 93: 95, 107: 96, 122: 97, 67: 98, 114: 99, 105: 100, 88: 101, 71: 102, 
                     84: 103, 112: 104, 115: 105, 110: 106, 119: 107, 90: 108, 85: 109, 76: 110, 79: 111, 121: 112, 108: 113, 
                     117: 114, 68: 115, 87: 116, 78: 117, 89: 118, 116: 120, 111: 121, 120: 122, 109: 123, 118: 124, 69: 125, 
                     86: 126, 77: 127}
    cipherTextList = []
    decryptedText = ""
    cipherTextList = list(cipherText)
    for i in cipherTextList:
        i = int(ord(i))
        if i in decryptionKey.keys():
            decryptedText += chr(decryptionKey[i])
    return decryptedText

In [16]:
x = encryption("The wall outside my house is 4 feet high!")
print(x)

apX+FzZZ+ONWDsiX+Uo+pONDX+sD++GXXW+psTp:


In [17]:
print(decryption(x))

The wall outside my house is 4 feet high!


In [18]:
c = {0: 1, 2: 30, 3: 47, 4: 52, 5: 5, 6: 28, 7: 43, 8: 54, 9: 48, 10: 51, 11: 2, 12: 29, 13: 44, 14: 53, 15:6, 16: 27,
     17: 31, 18: 46, 19: 49, 20: 4, 21: 25, 22: 8, 23: 55, 24: 42, 25: 50, 26: 3, 27: 32, 28: 45, 29: 56, 30: 41, 31: 26, 
     32: 7, 33: 33, 34: 62, 35: 15, 36: 20, 37: 9, 38: 24, 39: 39, 40: 58, 41: 16, 42: 19, 43: 34, 44: 61, 45: 40, 46: 57, 
     47: 10, 48: 23, 49: 63, 50: 14, 51: 17, 52: 36, 53: 21, 54: 12, 55: 59, 56: 38, 57: 18, 58: 35, 59: 64, 60: 13, 61: 60, 
     62: 37, 63: 22, 64: 11}

In [19]:
d = []
for i in c.values():
    d.append(i)
for i in c.values():
    d.append(i+64)
e = {}
for i in range(len(d)):
    e[i] = d[i]
print(e)

{0: 1, 1: 30, 2: 47, 3: 52, 4: 5, 5: 28, 6: 43, 7: 54, 8: 48, 9: 51, 10: 2, 11: 29, 12: 44, 13: 53, 14: 6, 15: 27, 16: 31, 17: 46, 18: 49, 19: 4, 20: 25, 21: 8, 22: 55, 23: 42, 24: 50, 25: 3, 26: 32, 27: 45, 28: 56, 29: 41, 30: 26, 31: 7, 32: 33, 33: 62, 34: 15, 35: 20, 36: 9, 37: 24, 38: 39, 39: 58, 40: 16, 41: 19, 42: 34, 43: 61, 44: 40, 45: 57, 46: 10, 47: 23, 48: 63, 49: 14, 50: 17, 51: 36, 52: 21, 53: 12, 54: 59, 55: 38, 56: 18, 57: 35, 58: 64, 59: 13, 60: 60, 61: 37, 62: 22, 63: 11, 64: 65, 65: 94, 66: 111, 67: 116, 68: 69, 69: 92, 70: 107, 71: 118, 72: 112, 73: 115, 74: 66, 75: 93, 76: 108, 77: 117, 78: 70, 79: 91, 80: 95, 81: 110, 82: 113, 83: 68, 84: 89, 85: 72, 86: 119, 87: 106, 88: 114, 89: 67, 90: 96, 91: 109, 92: 120, 93: 105, 94: 90, 95: 71, 96: 97, 97: 126, 98: 79, 99: 84, 100: 73, 101: 88, 102: 103, 103: 122, 104: 80, 105: 83, 106: 98, 107: 125, 108: 104, 109: 121, 110: 74, 111: 87, 112: 127, 113: 78, 114: 81, 115: 100, 116: 85, 117: 76, 118: 123, 119: 102, 120: 82, 121

In [20]:
f = {}
for i in range(len(d)):
    f[d[i]] = i
print(f)

{1: 0, 30: 1, 47: 2, 52: 3, 5: 4, 28: 5, 43: 6, 54: 7, 48: 8, 51: 9, 2: 10, 29: 11, 44: 12, 53: 13, 6: 14, 27: 15, 31: 16, 46: 17, 49: 18, 4: 19, 25: 20, 8: 21, 55: 22, 42: 23, 50: 24, 3: 25, 32: 26, 45: 27, 56: 28, 41: 29, 26: 30, 7: 31, 33: 32, 62: 33, 15: 34, 20: 35, 9: 36, 24: 37, 39: 38, 58: 39, 16: 40, 19: 41, 34: 42, 61: 43, 40: 44, 57: 45, 10: 46, 23: 47, 63: 48, 14: 49, 17: 50, 36: 51, 21: 52, 12: 53, 59: 54, 38: 55, 18: 56, 35: 57, 64: 58, 13: 59, 60: 60, 37: 61, 22: 62, 11: 63, 65: 64, 94: 65, 111: 66, 116: 67, 69: 68, 92: 69, 107: 70, 118: 71, 112: 72, 115: 73, 66: 74, 93: 75, 108: 76, 117: 77, 70: 78, 91: 79, 95: 80, 110: 81, 113: 82, 68: 83, 89: 84, 72: 85, 119: 86, 106: 87, 114: 88, 67: 89, 96: 90, 109: 91, 120: 92, 105: 93, 90: 94, 71: 95, 97: 96, 126: 97, 79: 98, 84: 99, 73: 100, 88: 101, 103: 102, 122: 103, 80: 104, 83: 105, 98: 106, 125: 107, 104: 108, 121: 109, 74: 110, 87: 111, 127: 112, 78: 113, 81: 114, 100: 115, 85: 116, 76: 117, 123: 118, 102: 119, 82: 120, 99:

### To encrypt images:
- Create a padding around the image until the pixel values are in multiples of 128.
- Shuffle the pixels in the rows in the order of the key created.
- Shuffle the rows in the order of the key created.

The ASCII character space has only 126 characters: for the remaining 2 characters, I have used the rupee (₹) and the american dollar ($) symbols.